export const ERROR_CODES = {
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  BODY_VALIDATION_ERROR: 'BODY_VALIDATION_ERROR',
  API_ERROR: 'API_ERROR',
  UNKNOWN: 'UNKNOWN',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT'
} as const;
