export const ERROR_KEYS = {
  unknown: "UNKNOWN_ERROR",
  internal: "INTERNAL_ERROR",
  invalidParameters: "INVALID_PARAMETERS",
  badRequest: "BAD_REQUEST",
  notImage: "NOT_AN_IMAGE",
  invalidFileType: "INVALID_FILE_TYPE",
  notFound: "NOT_FOUND",
  zodError: "ZOD_ERROR",
  unauthorized: "UNAUTHORIZED",
  forbidden: "FORBIDDEN",
  alreadyExists: "ALREADY_EXISTS",
  invalidCredentials: "INVALID_CREDENTIALS",
  notImplemented: "NOT_IMPLEMENTED",
  fileSizeLimit: "FILE_SIZE_LIMIT",
  fileCountLimit: "FILE_COUNT_LIMIT",
  fileUploadError: "FILE_UPLOAD_ERROR",
  fileDownloadError: "FILE_DOWNLOAD_ERROR",
  fileDeleteError: "FILE_DELETE_ERROR",
  fileNotFound: "FILE_NOT_FOUND",
  emailNotSent: "EMAIL_NOT_SENT",
  contactCreationError: "CONTACT_CREATION_ERROR",
};

const errorMessages = {
  fr: {
    [ERROR_KEYS.unknown]: "Erreur inconnue",
    [ERROR_KEYS.internal]: "Erreur interne",
    [ERROR_KEYS.invalidParameters]: "Paramètres invalides",
    [ERROR_KEYS.badRequest]: "Requête invalide",
    [ERROR_KEYS.notImage]: "Ce fichier n'est pas une image",
    [ERROR_KEYS.invalidFileType]: "Type de fichier invalide",
    [ERROR_KEYS.notFound]: "Ressource introuvable",
    [ERROR_KEYS.zodError]: "Erreur de validation",
    [ERROR_KEYS.unauthorized]: "Non autorisé",
    [ERROR_KEYS.forbidden]: "Interdit",
    [ERROR_KEYS.alreadyExists]: "Existe déjà",
    [ERROR_KEYS.invalidCredentials]: "Identifiants invalides",
    [ERROR_KEYS.notImplemented]: "Non implémenté",
    [ERROR_KEYS.fileSizeLimit]: "Taille de fichier limitée",
    [ERROR_KEYS.fileCountLimit]: "Nombre de fichiers limité",
    [ERROR_KEYS.fileUploadError]: "Erreur lors de l'envoi de fichier",
    [ERROR_KEYS.fileDownloadError]: "Erreur lors du téléchargement de fichier",
    [ERROR_KEYS.fileDeleteError]: "Erreur lors de la suppression de fichier",
    [ERROR_KEYS.fileNotFound]: "Fichier introuvable",
    [ERROR_KEYS.emailNotSent]: "Email non envoyé",
    [ERROR_KEYS.contactCreationError]: "Erreur lors de la création de contact",
  },
  en: {
    [ERROR_KEYS.unknown]: "Unknown error",
    [ERROR_KEYS.internal]: "Internal error",
    [ERROR_KEYS.invalidParameters]: "Invalid parameters",
    [ERROR_KEYS.badRequest]: "Bad request",
    [ERROR_KEYS.notImage]: "This file is not an image",
    [ERROR_KEYS.invalidFileType]: "Invalid file type",
    [ERROR_KEYS.notFound]: "Resource not found",
    [ERROR_KEYS.zodError]: "Validation error",
    [ERROR_KEYS.unauthorized]: "Unauthorized",
    [ERROR_KEYS.forbidden]: "Forbidden",
    [ERROR_KEYS.alreadyExists]: "Already exists",
    [ERROR_KEYS.invalidCredentials]: "Invalid credentials",
    [ERROR_KEYS.notImplemented]: "Not implemented",
    [ERROR_KEYS.fileSizeLimit]: "File size limit",
    [ERROR_KEYS.fileCountLimit]: "File count limit",
    [ERROR_KEYS.fileUploadError]: "File upload error",
    [ERROR_KEYS.fileDownloadError]: "File download error",
    [ERROR_KEYS.fileDeleteError]: "File delete error",
    [ERROR_KEYS.fileNotFound]: "File not found",
    [ERROR_KEYS.emailNotSent]: "Email not sent",
    [ERROR_KEYS.contactCreationError]: "Contact creation error",
  },
};

export const getErrorMessage = (
  errorKey: keyof typeof ERROR_KEYS,
  locale: "fr" | "en" = "fr",
) => {
  return errorMessages[locale][errorKey];
};
