version: "3"

services:
  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network
  mysql:
    image: mysql:latest
    container_name: collect_and_verything_db
    environment:
      MYSQL_ROOT_PASSWORD: collect
      MYSQL_DATABASE: collect_and_verything_db
      MYSQL_USER: mns_groupe2
      MYSQL_PASSWORD: collect
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

    # Define a network, which allows containers to communicate
    # with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
