services:
  mysql:
    image: mysql:latest
    container_name: ce_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - ce_network
  redis:
    image: redis:latest
    container_name: ce_redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - ce_network

volumes:
  mysql_data:
  redis_data:

networks:
  ce_network:
    name: ce_network
