version: "4"

services:
  company-users:
    container_name: company-users
    build:
      context: ../
      dockerfile: ./apps/company-users/Dockerfile
    ports:
      - ${COMPANY_USERS_PORT}:${COMPANY_USERS_PORT}
    restart: always
    networks:
      - ce_network

networks:
  ce_network:
    external: true
