version: "3"

services:
  database:
    image: mysql:latest
    container_name: collect_everything_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - ce_network
  company-users:
    container_name: company-users
    build:
      context: ../
      dockerfile: ./apps/company-users/Dockerfile
    ports:
      - ${COMPANY_USERS_PORT}:${COMPANY_USERS_PORT}
    restart: always
    networks:
      - ce_network

volumes:
  mysql_data:

networks:
  ce_network:
