services:
  showcase-gateway:
    container_name: showcase-gateway
    build:
      context: ../
      dockerfile: ./apps/showcase-gateway/Dockerfile
    ports:
      - ${SHOWCASE_GATEWAY_PORT}:${SHOWCASE_GATEWAY_PORT}
    restart: always
    networks:
      - ce_network
  company-users:
    container_name: company-users
    build:
      context: ../
      dockerfile: ./apps/company-users/Dockerfile
    ports:
      - ${COMPANY_USERS_PORT}:${COMPANY_USERS_PORT}
    restart: always
    networks:
      - ce_network
  companies:
    container_name: companies
    build:
      context: ../
      dockerfile: ./apps/companies/Dockerfile
    ports:
      - ${COMPANIES_PORT}:${COMPANIES_PORT}
    restart: always
    networks:
      - ce_network
  email-validation:
    container_name: email-validation
    build:
      context: ../
      dockerfile: ./apps/email-validation/Dockerfile
    ports:
      - ${EMAIL_VALIDATION_PORT}:${EMAIL_VALIDATION_PORT}
    restart: always
    environment:
      REDIS_PASS: ${REDIS_PASS}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - ce_network
  auth:
    container_name: auth
    build:
      context: ../
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    restart: always
    networks:
      - ce_network

networks:
  ce_network:
    external: true
